In [2]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
    
obj = demo()
obj.test()

test() for the class and method


In [2]:
class demo1:
    def fact(self,n):
        return
    
p1 = demo1()
p1.fact(5)



In [20]:
class demo1:
     def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
        
p1=demo1() 
p1.fact(5)


120

In [23]:
def fact(n):
    if(n==0):
        return 1
    else:
        return n*fact(n-1)
    
fact(6)


720

In [25]:
class demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return 
    def display(self):
        print("a=",self,p1)
        print("b=",self.p2)
        
c1=demo2()
c1.accept(10,20)
c1.display()

a= <__main__.demo2 object at 0x03F92150> <__main__.demo1 object at 0x03CFD850>
b= 20


In [26]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))


300


In [27]:
class demo2:
    def __init__(self,a1,a2):
        self.a1=a1
        self.a2=a2
    def product(self,a1,a2):
        return a1*a2

c1=demo2(10,20)
print(c1.product(100,120))
        

12000


In [29]:
class demo2:
    def __init__(self,a1,a2):
        self.a1=a1
        self.a2=a2
    def division(self,a1,a2):
        return a1/a2

c1=demo2(10,20)
print(c1.division(100,120))
        

0.8333333333333334


In [1]:
import numpy as np
np.arange(1,20)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [2]:
import numpy as np
np.arange(1,20)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
import numpy as np
np.arange(2,20,2)


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
import numpy as np 